<?xml version="1.0"?>
<robot
    xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
    xmlns:xacro="http://www.ros.org/wiki/xacro"
    name="ackermann">

    <xacro:property name="M_PI" value="3.1415926535897931" />
    <xacro:property name="wheel_diameter" value="0.20" />
    <xacro:property name="wheel_width" value="0.10" />
    <xacro:property name="box" value="0.10" />
    <xacro:property name="x_wheel_separation" value="0.47" />
    <xacro:property name="y_wheel_separation" value="0.42" />
    <xacro:property name="body_length" value="0.40" />
    <xacro:property name="body_width" value="0.15" />
    <xacro:property name="body_height" value="0.20" />
    
    <material name="Red">
    	<color rgba="1.0 0 0 1.0"/>
    </material>
    <material name="Green">
    	<color rgba="0 1.0 0 1.0"/>
    </material>
    <material name="Blue">
    	<color rgba="0 0 1.0 0.5"/>
    </material>


    <!-- Main body -->
    <link name="base_link">
        <inertial>
            <mass value="0.2" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.2" ixy="0.0"  ixz="0.0"  iyy="0.2"  iyz="0.0"  izz="0.2" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
            <material name="Blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <!-- Front link of Ackermann -->
    <joint name="front_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="front_link"/>
    	<origin xyz="${x_wheel_separation/2} 0.0 -0.15"/>
    </joint>
    <link name="front_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="0.02 ${y_wheel_separation} 0.005" />
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.02 ${y_wheel_separation} 0.005" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Red</material>
    </gazebo>
    
    <!-- a link aligned with the steer direction -->
    <joint name="steer_joint" type="fixed" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="steer_link" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </joint>
    <link name="steer_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="0.04 0.02 0.005" />
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="0.02 0 0" />
            <geometry>
                <box size="0.04 0.02 0.005" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="steer_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- the left Ackermann bar -->
    <joint name="front_left_bar_joint" type="fixed" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_left_bar_link" />
        <origin xyz="0.0 ${y_wheel_separation/2} 0.0" rpy="0 0 0" />
    </joint>
    <link name="front_left_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="0.04 0.02 0.005" />
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="0.04 0.02 0.005" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_bar_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- the right Ackermann bar -->
    <joint name="front_right_bar_joint" type="fixed" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_right_bar_link" />
        <origin xyz="0.0 -${y_wheel_separation/2} 0.0" rpy="0 0 0" />
    </joint>
    <link name="front_right_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="0.04 0.02 0.005" />
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="0.04 0.02 0.005" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_bar_link">
        <material>Gazebo/Red</material>
    </gazebo>

	<!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="fixed" >
        <axis xyz="0 1 0" />
        <parent link="front_left_bar_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_wheel_link">
        <material>Gazebo/Green</material>
    </gazebo>

	<!-- the front right wheel -->
    <joint name="front_right_wheel_joint" type="fixed" >
        <axis xyz="0 1 0" />
        <parent link="front_right_bar_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_wheel_link">
        <material>Gazebo/Green</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

	<!-- the Ackerman bar -->
    <joint name="ackermann_joint" type="fixed" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="steer_link" />
        <child link="ackermann_bar_link" />
        <origin xyz="-0.04 0 0" rpy="0 0 0" />
    </joint>
    <link name="ackermann_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="0.02 ${y_wheel_separation} 0.01" />
            </geometry>
            <material name="Red"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.02 ${y_wheel_separation} 0.01" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="ackermann_bar_link">
        <material>Gazebo/Blue</material>
    </gazebo>

	<!-- Gazebo Ackermann loop joints -->
    <gazebo>
      <joint:hinge name="ackermann_left_bar_joint">
        <body1>ackermann_bar_link</body1>
        <body2>front_left_bar_link</body2>
        <anchor>ackermann_bar_link</anchor>
        <axis>0 0 1</axis>
        <anchorOffset>0 0.06 0</anchorOffset>
      </joint:hinge>
    </gazebo>
    <gazebo>
      <joint:hinge name="ackermann_right_bar_joint">
        <body1>ackermann_bar_link</body1>
        <body2>front_right_bar_link</body2>
        <anchor>ackermann_bar_link</anchor>
        <axis>0 0 1</axis>
        <anchorOffset>0 -0.06 0</anchorOffset>
      </joint:hinge>
    </gazebo>
    
	<!-- the back left wheel -->
    <joint name="back_left_wheel_joint" type="fixed" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="-${x_wheel_separation/2} ${y_wheel_separation/2} -0.15" rpy="0 0 0" />
    </joint>
    <link name="back_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="back_left_wheel_link">
        <material>Gazebo/Green</material>
    </gazebo>
    
	<!-- the back right wheel -->
    <joint name="back_right_wheel_joint" type="fixed" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="-${x_wheel_separation/2} -${y_wheel_separation/2} -0.15" rpy="0 0 0" />
    </joint>
    <link name="back_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="back_right_wheel_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- Ackermann plugin -->
    <gazebo>
      <controller:ackermann_plugin name="ackermann_controller"
			           plugin="libackermann_plugin.so">
	<alwaysOn>true</alwaysOn>
	<update>100</update>
	<updateRate>100.0</updateRate>
	<leftJoint>back_left_wheel_joint</leftJoint>
	<rightJoint>back_right_wheel_joint</rightJoint>
	<steerJoint>steer_joint</steerJoint>
	<wheelSeparationWidth>0.16</wheelSeparationWidth>
	<wheelSeparationLength>0.32</wheelSeparationLength>
        <!-- Shouldn't this wheel diameter include the tire?
             (40 cm is about right for the bare rim)
          -->
	<wheelDiameter>0.041</wheelDiameter>
	<driveTorque>5</driveTorque>
	<steerTorque>5</steerTorque>
	<interface:position name="position_iface_0" />
	<robotNamespace>/</robotNamespace>
	<topicName>pilot/drive</topicName>
      </controller:ackermann_plugin>
      
     <canonicalBody>base_footprint</canonicalBody>

    <!-- this publishes empty joint_states due to no transmission, but
    triggering robot_state_publisher to publish tf between fixed joints in erratic,
    (e.g. base_laser_link for the base_scan frame) -->
    <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <interface:audio name="gazebo_ros_controller_manager_dummy_iface" />
    </controller:gazebo_ros_controller_manager>
      
    </gazebo>
    
        <joint name="sensors_base_mount_joint" type="fixed">
            <origin xyz="0.3 0 0.1" rpy="0 0 0" /> 
            <parent link="base_link"/>
            <child link="sensors_base_link"/>
        </joint>
        
        <link name="sensors_base_link" type="fixed">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0.0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.05 0.18 0.03"/>
                </geometry>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.05 0.18 0.03"/>
                </geometry>
            </collision>
        </link>
        
        <joint name="radar_joint" type="fixed" >
            <origin xyz="0.0275 0 0.005" rpy="${M_PI/2} 0 0" />
            <parent link="sensors_base_link" />
            <child link="radar_link"/>
        </joint>

        <joint name="imu_joint" type="fixed" >
            <origin xyz="0 0.06 0.02" rpy="${M_PI} 0 0" />
            <parent link="sensors_base_link" />
            <child link="imu_link"/>
        </joint>

        <joint name="gnss_joint" type="fixed" >
            <origin xyz="0 0 0.0275" rpy="0 0 0" />
            <parent link="sensors_base_link" />
            <child link="gnss_link"/>
        </joint>
        
        <link name="radar_link">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0.0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="0.0075 0 0"/>
                <geometry>
                    <box size="0.03 0.015 0.005" />
                </geometry>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.03 0.015 0.005" />
                </geometry>
            </collision>
        </link>

        <link name="imu_link">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.03 0.03 0.01" />
                </geometry>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.03 0.03 0.01" />
                </geometry>
            </collision>
        </link>

        <link name="gnss_link">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0.0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.06 0.05 0.025" />
                </geometry>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.06 0.05 0.025" />
                </geometry>
            </collision>
        </link>
        
        <gazebo reference="sensors_base_link">
            <material>Gazebo/Green</material>
        </gazebo>
	
        <gazebo reference="radar_link">
            <material>Gazebo/Green</material>
        </gazebo>
    
        <gazebo reference="imu_link">
            <material>Gazebo/Red</material>
        </gazebo>

        <gazebo reference="gnss_link">
            <material>Gazebo/Blue</material>
        </gazebo>
</robot>
